
version: "3.0"

services:
  nginx:
    image: nginx
    labels:
      kompose.service.type: LoadBalancer
    restart: on-failure
    container_name: nginx
    volumes:
      - ./nginx/sites-enabled:/etc/nginx/conf.d
    depends_on:
      - backend
    ports:
      - 80:80

  backend:
    image: swarm1/backend:v1.0.2
    restart: on-failure
    container_name: backend
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 80

  redis:
    image: redis
    restart: on-failure
    container_name: redis
    ports:
      - 6379

  mysql:
    image: mysql:8
    restart: on-failure
    container_name: mysql
    ports:
      - 3306
    environment:
      - MYSQL_DATABASE=virull_development
      - MYSQL_USER=virull
      - MYSQL_PASSWORD=changeme
      - MYSQL_ROOT_PASSWORD=changeme
    volumes:
      - ./mysql-initdb.d:/docker-entrypoint-initdb.d
